=begin
CDRH API

API to access all public Center for Digital Research in the Humanities resources

OpenAPI spec version: 0.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

class CollectionController < ApplicationController

  def show
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def collection_shortname_info_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def collection_shortname_item_id_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
