=begin
CDRH API

API to access all public Center for Digital Research in the Humanities resources

OpenAPI spec version: 0.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

class CollectionController < ApplicationController


  def index
    req = {
      "aggs" => {
        "typesAgg" => {
          "terms" => {
            "field" => "_type",
            "size" => 200
          }
        }
      },
      "size" => 0
    }
    body = post_search req
    # display error and do not continue
    return true if !body

    collections = body.dig("aggregations", "typesAgg", "buckets")
    collections = {} if !collections

    render json: JSON.pretty_generate({
      "res" => { "code" => 200 },
      # TODO would we rather that collection -> endpoint was a key value pair
      # instead of separate arrays?
      # TODO also elasticsearch returns the documents from each one in this query
      # so it would be easy to return if we built that in, also
      # technically the commented out below is what is in our open api schema atm
      # "info" => {
      #   "endpoints" => [],
      #   "collections" => [],
      # }
      "info" => {
        "collections" => collections
      }
    })
  end

  def show
    # code
    # info
    #   collection # def collection
    #   endpoints []
    #   fields
    #     # common
    #     # collection specific

    render json: {"message" => "collection show"}
  end

end
